# docker-compose.yaml (Final Version with Redis)

services:
  # NEW: The Redis in-memory data store
  redis:
    image: "redis:alpine" # Use a lightweight official Redis image
    container_name: redis-db
    networks:
      - bandit-net

  # The Slot Machine API Service (no changes)
  slot-machine-api:
    build:
      context: .
      dockerfile: src/slot_machine_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - bandit-net

  # The RL Agent - now connects to Redis
  rl-agent:
    build:
      context: .
      dockerfile: src/rl_agent/Dockerfile
    deploy:
      replicas: 1
    depends_on:
      - slot-machine-api
      - redis # Add dependency on Redis
    networks:
      - bandit-net
    # The 'volumes' section is now removed from the agent

  # The Visualizer - now connects to Redis
  visualizer:
    build:
      context: .
      dockerfile: src/visualizer/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - redis
    networks:
      - bandit-net
    # The 'volumes' section is now removed from the visualizer

networks:
  bandit-net:
    driver: bridge

# We no longer need the top-level 'volumes' declaration for agent-data
# as it's been replaced by Redis.