# docker-compose.yaml (Scaling Enabled)
services:
  slot-machine-api:
    build:
      context: .
      dockerfile: src/slot_machine_api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - bandit-net

  rl-agent:
    build:
      context: .
      dockerfile: src/rl_agent/Dockerfile
    deploy:
      replicas: 10 # Scaling back to 10 instances
    depends_on:
      - slot-machine-api
    volumes:
      - agent-data:/data
    networks:
      - bandit-net

  visualizer:
    build:
      context: .
      dockerfile: src/visualizer/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - rl-agent
    volumes:
      - agent-data:/data:ro
    networks:
      - bandit-net

networks:
  bandit-net:
    driver: bridge

volumes:
  agent-data:
    driver: local