# docker-compose.yaml

version: '3.8'

services:
  # The Slot Machine API Service
  slot-machine-api:
    build:
      context: .
      dockerfile: src/slot_machine_api/Dockerfile
    container_name: slot-machine-api-1
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    networks:
      - bandit-net

  # The Reinforcement Learning Agent Service
  rl-agent:
    build:
      context: .
      dockerfile: src/rl_agent/Dockerfile
    container_name: rl-agent-1
    # 'depends_on' ensures the API container starts before the agent container
    depends_on:
      - slot-machine-api
    # Mount the 'agent-data' volume to persist the agent's state
    volumes:
      - agent-data:/data
    networks:
      - bandit-net

# Define the network that allows containers to communicate by service name
networks:
  bandit-net:
    driver: bridge

# Define the volume that will store our agent's persistent data
volumes:
  agent-data:
    driver: local