# kubernetes/visualizer-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: visualizer-service
spec:
  type: NodePort
  selector:
    app: visualizer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
      nodePort: 30081
